// Code generated by protoc-gen-kit. DO NOT EDIT.

package testv1

import (
	context "context"
	grpc "github.com/go-kit/kit/transport/grpc"
	subtest "github.com/sagikazarmark/protoc-gen-kit/test/subtest"
)

// TestServiceKitServer is the Go kit server implementation for TestService service.
type TestServiceKitServer struct {
	*UnimplementedTestServiceServer

	TestProcedureHandler   grpc.Handler
	SubestProcedureHandler grpc.Handler
}

func (s TestServiceKitServer) TestProcedure(ctx context.Context, req *TestProcedureRequest) (*TestProcedureResponse, error) {
	_, resp, err := s.TestProcedureHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*TestProcedureResponse), nil
}

func (s TestServiceKitServer) SubestProcedure(ctx context.Context, req *subtest.SubtestProcedureRequest) (*subtest.SubtestProcedureResponse, error) {
	_, resp, err := s.SubestProcedureHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*subtest.SubtestProcedureResponse), nil
}
